language: scala
scala:
   - 2.11.7
branches:
  only:
    - master
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION one-jar
