language: scala
scala:
   - 2.11.12
branches:
  only:
    - master
jdk:
  - openjdk9

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION one-jar
