language: scala
scala:
   - 2.11.7
branches:
  only:
    - master
jdk:
  - openjdk10

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION one-jar
